/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.trabalho;
import java.util.*;
import java.time.*;
import java.time.format.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.persistence.EntityManager;
import javax.persistence.RollbackException;
/**
 *
 * @author loize
 */
public class TelaCadastro extends javax.swing.JFrame {
    //criando um arrayList para armazenar os alunos
    private ArrayList<Aluno> listaAlunos = new ArrayList<>(); 
    //quantidade de alunos ja cadastrados;
    private int quantTotal = 0;
    //caminho para o arquivo clientes do jpanelLeituraArq
    private static final String NOME_ARQUIVO = "ListagemAlunos.txt";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPaneInserir = new javax.swing.JOptionPane();
        jDialogAlerta = new javax.swing.JDialog();
        jLabelMensagem = new javax.swing.JLabel();
        jOptionPaneAlerta = new javax.swing.JOptionPane();
        jPanelCadastro = new javax.swing.JPanel();
        jLabelIdade = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jLabelDataNasc = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataNasc = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonNovoVelho = new javax.swing.JButton();
        jButtonInserirPosicao = new javax.swing.JButton();
        jButtonLer = new javax.swing.JButton();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldMatricula = new javax.swing.JFormattedTextField();
        jButtonLimpar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialogAlertaLayout = new javax.swing.GroupLayout(jDialogAlerta.getContentPane());
        jDialogAlerta.getContentPane().setLayout(jDialogAlertaLayout);
        jDialogAlertaLayout.setHorizontalGroup(
            jDialogAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAlertaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogAlertaLayout.setVerticalGroup(
            jDialogAlertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAlertaLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanelCadastro.setBackground(new java.awt.Color(225, 225, 225));
        jPanelCadastro.setForeground(new java.awt.Color(255, 255, 255));
        jPanelCadastro.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jLabelIdade.setText("Idade:");

        jLabelCpf.setText("CPF:");

        jLabelDataNasc.setText("Data de Nascimento:");

        jLabelNome.setText("Nome:");

        jLabelTelefone.setText("Telefone/Celular:");

        jLabelMatricula.setText("Matrícula:");

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCpf.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jFormattedTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldCpfActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataNasc.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jTextFieldNome.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jTextFieldIdade.setEditable(false);
        jTextFieldIdade.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonNovoVelho.setText("Novo/Velho");
        jButtonNovoVelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVelhoActionPerformed(evt);
            }
        });

        jButtonInserirPosicao.setText("Inserir Posição");
        jButtonInserirPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirPosicaoActionPerformed(evt);
            }
        });

        jButtonLer.setText("Ver Alunos");
        jButtonLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLerActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        jFormattedTextFieldMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        jFormattedTextFieldMatricula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jFormattedTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldMatriculaActionPerformed(evt);
            }
        });

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelDataNasc)
                                .addGap(0, 136, Short.MAX_VALUE))
                            .addComponent(jLabelCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDataNasc)
                            .addComponent(jTextFieldNome))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadastroLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(84, 84, 84))
                    .addGroup(jPanelCadastroLayout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNovoVelho)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInserirPosicao)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonNovoVelho)
                    .addComponent(jButtonInserirPosicao)
                    .addComponent(jButtonLer)
                    .addComponent(jButtonLimpar))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void jFormattedTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldMatriculaActionPerformed

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void jButtonLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLerActionPerformed
        // TODO add your handling code here:
        JFrameLeituraArq leituraArq = new JFrameLeituraArq();     /* JFrameLeituraArq é um novo jFrame que eu criei só para exibir os aluno */
        leituraArq.setVisible(true);
    }//GEN-LAST:event_jButtonLerActionPerformed

    private void jButtonInserirPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirPosicaoActionPerformed
        // TODO add your handling code here:
        EntityManager em = null;
        try {
            //para formatação da data
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            String nome = jTextFieldNome.getText().trim();
            String matricula = jFormattedTextFieldMatricula.getText().trim();
            String dataNascTexto = jFormattedTextFieldDataNasc.getText().trim();
            String cpf = jFormattedTextFieldCpf.getText().trim();
            String telefone = jFormattedTextFieldTelefone.getText().trim();

            boolean temCampoVazio = existeCamposVazios(nome,matricula,dataNascTexto,cpf,telefone);
            if (temCampoVazio){
                return;
            }

            // Conversão da data e inserção de idade no campo jTextFieldIdade
            LocalDate dataNasc = LocalDate.parse(dataNascTexto, fmt);
            int idade = calculaIdade(dataNasc);
            jTextFieldIdade.setText(Integer.toString(idade));

            //Instanciando Aluno
            Aluno alunoParaInserir = new Aluno(matricula,nome,dataNasc,telefone,cpf, idade);

            //usando JOptionPane para pedir a posição onde o usuario quer inserir o aluno
            String inputPos = jOptionPaneInserir.showInputDialog(
                this, "Digite a posição onde deseja inserir o aluno:",
                "Inserir em Posição", // Título da caixa de diálogo
                jOptionPaneInserir.QUESTION_MESSAGE
            ); //"this" é a TelaCadastro

            // Verifica se o usuário clicou "Cancelar" ou não digitou nada
            if (inputPos != null && !inputPos.isEmpty()) {
                // Converte o texto para um número inteiro
                int pos = Integer.parseInt(inputPos);
                    //inserçaõ no banco
                try{
                   em = JPAUtil.getEntityManagerFactory().createEntityManager();
                   em.getTransaction().begin();
                   em.persist(alunoParaInserir);
                   em.getTransaction().commit();
                }catch(RollbackException e){
                    jOptionPaneAlerta.showMessageDialog(this, "Erro ao salvar no banco: A Matrícula '" + matricula + "' já existe!", "Erro de Duplicidade", JOptionPane.ERROR_MESSAGE);
                    return;
                }catch (Exception e) {
                    jOptionPaneAlerta.showMessageDialog(this, "Erro inesperado ao conectar no banco: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }finally{
                    if (em != null) {
                        em.close();
                    }
                }
                // Chama o metodo para inserção no csv
                inserePosicao(pos, alunoParaInserir);
                ArquivoCSV.salvarAluno(listaAlunos);
                // Mostrando sucesso para o usuário
                jOptionPaneInserir.showMessageDialog(this, "Aluno inserido com sucesso na posição " + pos + "!", "Sucesso", jOptionPaneInserir.INFORMATION_MESSAGE);
            } else {
                jOptionPaneInserir.showMessageDialog(this, "Operação de inserção cancelada.", "Aviso", jOptionPaneInserir.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e){//verifica se a informação condiz com o tipo pedido
            jOptionPaneAlerta.showMessageDialog(this, "Formato inválido",
                "Erro", jOptionPaneAlerta.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            jOptionPaneAlerta.showMessageDialog(this, "Erro: " + e.getMessage(),
                "Erro", jOptionPaneAlerta.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInserirPosicaoActionPerformed

    private void jButtonNovoVelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVelhoActionPerformed
       
        if (listaAlunos.isEmpty()) {
            jOptionPaneAlerta.showMessageDialog(this, "Erro: Lista Vazia.", "Alerta", jOptionPaneAlerta.ERROR_MESSAGE);
            return;
        }
        
        String resultado = ComparacaoIdade();
        jOptionPaneAlerta.showMessageDialog(this, resultado, "Comparação de Idade", jOptionPaneAlerta.INFORMATION_MESSAGE);         
    }//GEN-LAST:event_jButtonNovoVelhoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
       // TODO add your handling code here:
        String matricula = jFormattedTextFieldMatricula.getText().trim();
        //verifica se a matricula na jTextField é valida ou se foi preenchida
        if (matricula.trim().isEmpty()) {
            jOptionPaneAlerta.showMessageDialog(this, "Matrícula é obrigatória!",
                "Aviso", jOptionPaneAlerta.WARNING_MESSAGE);
            return;
        }

        boolean removido = excluirAluno(matricula); // chama a função e recebe o seu retorno

        //utiliza o valor do retorno para verificação
        if(removido){
            jOptionPaneAlerta.showMessageDialog(this, "Matricula " + matricula +"removida!",
                "Aluno Removido", jOptionPaneAlerta.INFORMATION_MESSAGE);
            ArquivoCSV.salvarAluno(listaAlunos);
            return;
        }
        jOptionPaneAlerta.showMessageDialog(this, "Aluno com matrícula " + matricula + " não encontrado.",
            "Aviso", jOptionPaneAlerta.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
            String matricula = jFormattedTextFieldMatricula.getText().trim();
            
            if (matricula.trim().isEmpty()) {
                jOptionPaneAlerta.showMessageDialog(this, "Matrícula é obrigatória!",
                    "Erro", jOptionPaneAlerta.WARNING_MESSAGE);
                return;
            }
            
            Aluno alunoBuscado = buscaAluno(matricula);

            if(alunoBuscado != null){
                jOptionPaneAlerta.showMessageDialog(this, "Aluno: " + alunoBuscado.getNome()+"\nMatrícula: " +alunoBuscado.getMatr()
                                                    +"\nCPF: " +alunoBuscado.getCpf() + "\nTelefone: " + alunoBuscado.getTelefone()
                                                    + "\nData de Nascimento: " + alunoBuscado.getDataNasc(),
                                                "Aluno Encontrado", jOptionPaneAlerta.INFORMATION_MESSAGE);
                return;
            }
            jFormattedTextFieldMatricula.setText("");
            jOptionPaneAlerta.showMessageDialog(this, "Aluno não encontrado! ",
                    "Alerta", jOptionPaneAlerta.WARNING_MESSAGE);
                       
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        // TODO add your handling code here:
        EntityManager em = null;
        try{
            //para formatação da data
            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            String nome = jTextFieldNome.getText().trim();
            System.out.println("Nome: " + nome);
            
            String matricula = jFormattedTextFieldMatricula.getText().trim();
            System.out.println("Matricula: " + matricula);
            
            String dataNascTexto = jFormattedTextFieldDataNasc.getText().trim();
            System.out.println("Data: " + dataNascTexto);
            
            String cpf = jFormattedTextFieldCpf.getText().trim();
            System.out.println("cpf: " + cpf);
            
            String telefone = jFormattedTextFieldTelefone.getText().trim();
            System.out.println("telefone: " + telefone);

            boolean temCampoVazio = existeCamposVazios(nome,matricula,dataNascTexto, cpf,telefone);
            if (temCampoVazio){
                return;
            }
            // Conversão da data
            LocalDate dataNasc = LocalDate.parse(dataNascTexto, fmt);
            int idade = calculaIdade(dataNasc);
            jTextFieldIdade.setText(Integer.toString(idade));

            // Chamada do método de cadastro
            Aluno novoAluno = cadastroAluno(matricula, telefone, cpf, idade, nome, dataNasc);
            
            //chama o metodo 
            em = JPAUtil.getEntityManagerFactory().createEntityManager();
            em.getTransaction().begin();
            em.persist(novoAluno);
            em.getTransaction().commit();
            System.out.println("Salvo"); 
            //arquivo
            ArquivoCSV.salvarAluno(listaAlunos);
            
            jOptionPaneAlerta.showMessageDialog(this, "Aluno cadastrado com suceso!\n Nome: "+ novoAluno.getNome() +
                "\nMatrícula: " + novoAluno.getMatr() + "\nTotal de alunos: " + quantTotal,
                "CADASTRO BEM SUCEDIDO", jOptionPaneAlerta.INFORMATION_MESSAGE);


              

            
        }catch (NumberFormatException e) {
            jOptionPaneAlerta.showMessageDialog(this, "Erro: idade inválida (digite um número inteiro).",
                "Erro", jOptionPaneAlerta.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
            jOptionPaneAlerta.showMessageDialog(this, "Erro: data inválida! Use o formato DD/MM/AAAA.",
                "Erro", jOptionPaneAlerta.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            jOptionPaneAlerta.showMessageDialog(this, "Erro: " + e.getMessage(),
                "Erro", jOptionPaneAlerta.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jFormattedTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCpfActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        jTextFieldNome.setText("");
        jFormattedTextFieldMatricula.setText(""); // ou setText(null);
        jFormattedTextFieldDataNasc.setText(""); // ou setText(null);
        jFormattedTextFieldCpf.setText(""); // ou setText(null);
        jFormattedTextFieldTelefone.setText(""); // ou setText(null);
        jTextFieldIdade.setText("");
    
        // Foca o cursor no primeiro campo, pronto para o próximo cadastro
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    //método para testar campos vazios
    private boolean existeCamposVazios(String nome, String matricula, String dataNasc, String cpf, String telefone ){
        if (nome.trim().isEmpty()) {
            jOptionPaneAlerta.showMessageDialog(this, "Nome é obrigatório!", 
                                               "Aviso", jOptionPaneAlerta.WARNING_MESSAGE); 
            return true;
        }else if(matricula.trim().isEmpty()) {
           jOptionPaneAlerta.showMessageDialog(this, "Matrícula é obrigatória!", 
                                              "Aviso", jOptionPaneAlerta.WARNING_MESSAGE); 
            return true;
        }else if(dataNasc.equals("  /  /    ") ) {
           jOptionPaneAlerta.showMessageDialog(this, "Data de Nascimento é obrigatória!", 
                                              "Aviso", jOptionPaneAlerta.WARNING_MESSAGE); 
            return true;
        }else if(cpf.equals(" .   .   -  ")){
           jOptionPaneAlerta.showMessageDialog(this, "Cpf é obrigatório!", 
                                              "Aviso", jOptionPaneAlerta.WARNING_MESSAGE);
           return true;
        }else if(telefone.equals(" (  )     -")){
           jOptionPaneAlerta.showMessageDialog(this, "Telefone é obrigatório!", 
                                             "Aviso", jOptionPaneAlerta.WARNING_MESSAGE);                  
           return true;
        }

        return false;
    } 
    
    //método para calcular a idade do aluno e "setar" no campo jTextFieldIdade
    private int calculaIdade(LocalDate dataNasc) {
        return Period.between(dataNasc, LocalDate.now()).getYears();
    }
    
    // Método de  cadastro
    public Aluno cadastroAluno(String matricula, String telefone, String cpf, int idade, String nome, LocalDate dataNasc) {
        
        //instanciação de ALUNO
        Aluno aluno = new Aluno(matricula, nome, dataNasc, telefone, cpf, idade);
        
        //tratamento de erro
        for (Aluno a : listaAlunos) {
            if (matricula.equals(a.getMatr())) {
                throw new IllegalArgumentException("Matrícula já cadastrada!");                 
            }
        }
        //adiciona o aluno
        listaAlunos.add(aluno);
        quantTotal++;

        return aluno;
    }
    
    //Metodo para encontrar aluno mais velho e mais novo
    public String ComparacaoIdade(){
        int menor = Integer.MAX_VALUE, maior = Integer.MIN_VALUE;
        String tempMenor = "", tempMaior = ""; 
        
        for(Aluno a : listaAlunos){
            if(a.getIdade() > maior){
               tempMaior = a.getMatr();
               maior = a.getIdade();
            }
            if(a.getIdade() < menor){
               tempMenor = a.getMatr();
               menor = a.getIdade();
            }            
        }
        return "Mais velho: " + tempMaior + " (" + maior + " anos)\n" + "Mais novo: " + tempMenor + " (" + menor + " anos)";

    }

    //Método de pesquisa
    public Aluno buscaAluno(String matricula) { 
        for (Aluno a : listaAlunos) {
            if (matricula.equals(a.getMatr())) {
                return a; // Retorna o OBJETO Aluno
            }
        }
        return null; 
    }
    
    /*Metodo para exclusão de um aluno da lista
      Classe RemocaoAlunoDAO que implementa a Interface AlunoDAO*/
    public boolean excluirAluno(String matricula){
        EntityManager em = null;
        try {
                em = JPAUtil.getEntityManagerFactory().createEntityManager();
                em.getTransaction().begin();

                //Encontra o aluno no banco de dados
                Aluno alunoRemover = em.find(Aluno.class, matricula);

                if (alunoRemover != null) {
                    em.remove(alunoRemover);

                    em.getTransaction().commit();

                    AlunoDAO dao = new RemocaoAlunoDAO();
                    Aluno alunoLista = null;
                    for (Aluno alunoTemp : listaAlunos) {
                        if (matricula.equals(alunoTemp.getMatr())) {
                            alunoLista = alunoTemp;
                            break;
                        }
                    }
                    if (alunoLista != null) {
                        dao.removerAluno(listaAlunos, alunoLista);
                        quantTotal--;
                    }
                    return true;
                    
                } else {
                    em.getTransaction().rollback();
                    return false;
                }

            } catch (Exception e) {
                System.err.println("Erro ao excluir aluno: " + e.getMessage());
                e.printStackTrace();
                // Desfaz a transação
                if (em != null && em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                return false;
            } finally {
                if (em != null) {
                    em.close();
                }
            }
    }
     
    //Metodo para inserção em posições especificas
    public void inserePosicao(int pos, Aluno aluno){
        if (pos < 0 || pos > listaAlunos.size()) {
            throw new IllegalArgumentException("Posição inválida. A posição deve estar entre 0 e " + listaAlunos.size() + ".");}
        else listaAlunos.add(pos, aluno);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        TelaCadastro telaCadastro = new TelaCadastro();
        telaCadastro.setVisible(true);
        telaCadastro.setLocationRelativeTo(null);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonInserirPosicao;
    private javax.swing.JButton jButtonLer;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonNovoVelho;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JDialog jDialogAlerta;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldMatricula;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelDataNasc;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JOptionPane jOptionPaneAlerta;
    private javax.swing.JOptionPane jOptionPaneInserir;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
